### PR TITLE
WIP make the code compile with libecl version-2.7. 

### PR DESCRIPTION
**Pull request by totto82**
The build system finds libecl (I have build  an older 2.7 version in my local folder (i.e. not installed it)

I hardcoded
```cmake
include_directories(${CMAKE_SOURCE_DIR}/../libecl/lib/include)
include_directories(${CMAKE_SOURCE_DIR}/../libecl/build/lib/include)
```
for the code to find the header files, and then the library part build fine, but when building the application it does not find the libecl functions. 

Any hint on how this should be done would be appreciated.

### CODE REVIEW

**Comment by akva2** [comment]
ecl is no longer found using sibling search.

either install it on your system or use cmake -Decl_DIR=<path/to/your/ecl/build/directory>

**Comment by totto82** [comment]
> -Decl_DIR=<path/to/your/ecl/build/directory> 

didn't do the trick. I still have issues 

```
/home/AD.NORCERESEARCH.NO/tosa/workspace/opm/opm-flowdiagnostics-applications/opm/utility/ECLGraph.cpp:46:10: fatal error: ert/ecl/ecl_grid.h: No such file or directory
   46 | #include <ert/ecl/ecl_grid.h>
```
